name: Java CI with Gradle, Docker Multi-Arch, and Separate Testing

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Generate Kover HTML report
        run: ./gradlew koverHtmlReport

      - name: Generate Kover XML report
        run: ./gradlew koverXmlReport

      - name: Upload coverage HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-html-report
          path: build/reports/kover/htmlReport/

      - name: Upload coverage XML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-xml-report
          path: build/reports/kover/xmlReport.xml

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker images for both arm64 and amd64
        run: docker buildx build --platform linux/arm64,linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/truckers-api:latest --push .
